name: 'job_market_dbt'
version: '1.0.0'
config-version: 2

profile: 'job_market_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  bronze_schema: bronze
  silver_schema: silver
  gold_schema: gold

models:
  job_market_dbt:
    staging:
      +materialized: table
      +schema: "{{ var('bronze_schema') }}"
    intermediate:
      +materialized: table
      +schema: "{{ var('silver_schema') }}"
    marts:
      +materialized: table
      +schema: "{{ var('gold_schema') }}"